FROM eoscanada/eos-build-nodeos as builder

FROM ubuntu:18.04

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl less \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/*       /usr/local/lib/
COPY --from=builder /opt/eos/bin           /opt/eosio/bin
COPY --from=builder /tmp/build/contracts   /contracts
COPY --from=builder /eos/Docker/nodeosd.sh /opt/eosio/bin/nodeosd.sh

ENV LD_LIBRARY_PATH /usr/local/lib
ENV EOSIO_ROOT      /opt/eosio
ENV PATH            /opt/eosio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

VOLUME /opt/eosio/bin/data-dir

CMD ["/opt/eosio/bin/nodeos"]
